# Generated by Django 4.2.3 on 2023-07-21 21:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('full_name', models.CharField(help_text='Full name should contain only letters.', max_length=255, validators=[django.core.validators.RegexValidator(code='invalid_full_name', message='Full name should contain only letters.', regex='^[A-Za-z ]+$')])),
                ('iqama_number', models.CharField(help_text='IQAMA number must start with 1 or 2 and be 10 digits long.', max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='IQAMA number must start with 1 or 2 and be 10 digits long.', regex='^[1-2][0-9]{9}$')])),
                ('copy_of_iqama_number', models.ImageField(max_length=512, upload_to='copy_of_iqama_number')),
                ('mobile_number', models.CharField(default='', help_text='The mobile number should start with 5 and be 9 digits long.', max_length=9, unique=True, validators=[django.core.validators.RegexValidator(message='The mobile number should start with 5 and be 9 digits long.', regex='^5\\d{8}$')])),
                ('email', models.EmailField(default='', help_text='The email address should be unique and valid.', max_length=254, unique=True, validators=[django.core.validators.EmailValidator])),
                ('date_of_birth', models.DateField(help_text='The date of birth should be in the format dd-mm-yyyy.')),
                ('nationality', models.CharField(default='', help_text='The nationality should be a valid country code.', max_length=255)),
                ('password', models.CharField(max_length=128, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
