# Generated by Django 4.2.3 on 2023-08-31 00:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ekseer_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('doctor_id', models.IntegerField()),
                ('chief_complaint', models.CharField(max_length=255)),
                ('history_of_illness', models.CharField(max_length=255)),
                ('review_of_systems', models.CharField(max_length=255)),
                ('examination', models.CharField(max_length=255)),
                ('assessment', models.CharField(blank=True, max_length=255, null=True)),
                ('medication', models.CharField(blank=True, max_length=255, null=True)),
                ('sick_leave', models.IntegerField()),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
